apiVersion: apps/v1

kind: Deployment

metadata:
  name: backend-user

  labels:
    app: backend-user

spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
        - name: udagram-api-user
          image: docker.io/remidoragon/udagram-api-user:latest
          imagePullPolicy: Always
          
          ports:
            - containerPort: 8080
          
          envFrom:  
            - secretRef:
                name: env-secret
            - secretRef:
                name: aws-secret
            - configMapRef:
                name: configmap