apiVersion: apps/v1

kind: Deployment

metadata:
  name: backend-feed

  labels:
    app: backend-feed

spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
        - name: udagram-api-feed
          image: docker.io/remidoragon/udagram-api-feed:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8080

          envFrom:  
            - secretRef:
                name: env-secret
            - secretRef:
                name: aws-secret
            - configMapRef:
                name: configmap